apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    microservice.group: final-project
    io.kompose.service: ordersystem-service
  name: ordersystem-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordersystem-service
  template:
    metadata:
      labels:
#        io.kompose.network/services-network-01: "true"
        microservice.group: final-project
        io.kompose.service: ordersystem-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://PostgreSQL:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/ordersystem:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 8762
              path: /actuator/health
            failureThreshold: 5
            initialDelaySeconds: 100
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8762
              path: /actuator/health
            failureThreshold: 5
            initialDelaySeconds: 65
            periodSeconds: 5
            timeoutSeconds: 10
          name: ordersystem-service
          ports:
            - containerPort: 8762
          resources: {}
      hostname: ordersystem-service
      restartPolicy: Always
