apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    microservice.group: final-project
    io.kompose.service: ordersystem-service
  name: ordersystem-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ordersystem-service
  template:
    metadata:
      labels:
#        io.kompose.network/services-network-01: "true"
        microservice.group: final-project
        io.kompose.service: ordersystem-service
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: fpuser
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://10.5.160.3:5432/final-project-db
            - name: SPRING_DATASOURCE_USERNAME
              value: fpuser
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/ordersystem:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          livenessProbe:
            httpGet:
              port: 8762
              path: /actuator/health
            failureThreshold: 5
            initialDelaySeconds: 65
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8762
              path: /actuator/health
            failureThreshold: 5
            initialDelaySeconds: 40
            periodSeconds: 5
            timeoutSeconds: 10
          name: ordersystem-service
          ports:
            - containerPort: 8762
      hostname: ordersystem-service
      restartPolicy: Always
#  strategy:
#    type: Recreate

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 100%
