apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: raporting-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: raporting-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80