apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: registry
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: registry
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50