version: '3.7'
services:

  registry:
    build:
      context: .
      dockerfile: registry/Dockerfile
    image: fp-registry:latest
    hostname: registry
    expose:
      - "8761"
    networks:
      services-network-01:
        aliases:
          - registry
    healthcheck:
      test: "curl --fail --silent registry:8761/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      services-network-01:
        aliases:
          - postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: auth-service
    expose:
      - "8080"
    networks:
      services-network-01:
        aliases:
          - auth-service
    depends_on:
      - postgresql
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=postgres
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Pa55w0rd

  ordersystem-service:
    build:
      context: .
      dockerfile: ordersystem/Dockerfile
    image: fp-ordersystem-service:latest
    hostname: ordersystem-service
    expose:
      - "8762"
    networks:
      services-network-01:
        aliases:
          - ordersystem-service
    depends_on:
      - registry
      - postgresql
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent ordersystem-service:8762/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  store-service:
    build:
      context: .
      dockerfile: store/Dockerfile
    image: fp-store-service:latest
    hostname: store-service
    expose:
      - "8763"
    networks:
      services-network-01:
        aliases:
          - store-service
    depends_on:
      - registry
      - postgresql
      - ordersystem-service
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent store-service:8763/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s

  reporting-service:
    build:
      context: .
      dockerfile: reporting/Dockerfile
    image: fp-reporting-service:latest
    hostname: reporting-service
    expose:
      - "8764"
    networks:
      services-network-01:
        aliases:
          - reporting-service
    depends_on:
      - registry
      - postgresql
      - ordersystem-service
      - store-service
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent reporting-service:8764/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    image: fp-gateway:latest
    hostname: gateway
    ports:
      - "8760:8760"
    networks:
      services-network-01:
        aliases:
          - gateway
    depends_on:
      - ordersystem-service
      - store-service
      - reporting-service
      - registry
    restart: on-failure
    healthcheck:
      test: "curl --fail --silent gateway:8760/actuator/health | grep UP || exit 1"
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

networks:
  services-network-01:
    name: services-network-01
    driver: bridge

volumes:
  pgdata: