version: '3.7'
services:
  registry:
    build: ./registry
    image: fp-store-registry:latest
    container_name: registry
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - store-network
      aliases:
        - registry

  ordersystem-service:
    build: ./ordersystem
    image: fp-store-ordersystem:latest
    container_name: ordersystem-service
    expose:
      - 8762
    ports:
      - 8762:8762
    networks:
      - store-network
    links:
      - registry:registry
    depends_on:
      - registry

  gateway:
    build: ./gateway
    image: fp-store-gateway:latest
    container_name: gateway
    expose:
      - 8760
    ports:
      - 8760:8760
    networks:
      - store-network
    links:
      - registry:registry
    depends_on:
      - registry


networks:
  store-network:
    driver: bridge