version: '3.7'
services:

  registry:
    build:
      context: ./registry
    image: fp-registry:latest
    hostname: registry
    expose:
      - "8761"
    networks:
      services-network-01:
        aliases:
          - registry


  ordersystem-service:
    build:
      context: ./ordersystem
    hostname: ordersystem-service
    expose:
      - "8762"
    networks:
      services-network-01:
        aliases:
          - ordersystem-service
    depends_on:
      - registry

  store-service:
    build:
      context: ./store
    hostname: store-service
    expose:
      - "8763"
    networks:
      services-network-01:
        aliases:
          - store-service
    depends_on:
      - registry


  gateway:
    build:
      context: ./gateway
    hostname: gateway
    ports:
      - "8760:8760"
    networks:
      services-network-01:
        aliases:
          - gateway
    depends_on:
      - ordersystem-service
      - store-service
      - registry

networks:
  services-network-01:
    name: services-network-01
    driver: bridge