apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: final-project
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/gateway
    jib:
      project: gateway
  - image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/ordersystem
    jib:
      project: ordersystem
  - image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/raporting
    jib:
      project: raporting
  - image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/store
    jib:
      project: store
  - image: europe-west3-docker.pkg.dev/final-project-334521/fp-repo/registry
    jib:
      project: registry
deploy:
  kubectl:
    manifests:
#    - .k8s/postgresql-service.yaml
    - .k8s/gateway-deployment.yaml
    - .k8s/gateway-service.yaml
    - .k8s/gateway-hpa.yaml
    - .k8s/ordersystem-service-deployment.yaml
    - .k8s/ordersystem-service-service.yaml
    - .k8s/ordersystem-service-hpa.yaml
#    - .k8s/postgresql-deployment.yaml
    - .k8s/raporting-service-deployment.yaml
    - .k8s/raporting-service-service.yaml
    - .k8s/raporting-service-hpa.yaml
    - .k8s/registry-deployment.yaml
    - .k8s/registry-service.yaml
    - .k8s/registry-hpa.yaml
#    - .k8s/services-network-01-networkpolicy.yaml
    - .k8s/store-service-deployment.yaml
    - .k8s/store-service-service.yaml
    - .k8s/store-service-hpa.yaml
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
