spring:
  application:
    name: store-service
  datasource:
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 8763
  forward-headers-strategy: framework

info:
  app:
    name: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info