server:
  port: 8760

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: ordersystem-service
          uri: lb://ordersystem-service
          predicates:
            - Path=/ordersystem-service/**
          filters:
            - StripPrefix=1
#        - id: store
#          uri: lb://store
#          predicates:
#            - Path=/store/**
#          filters:
#            - StripPrefix=1
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**

info:
  app:
    name: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info