server:
  port: 8760
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ordersystem-service
          uri: lb://ordersystem-service
          predicates:
            - Path=/ordersystem-service/**
          filters:
            - StripPrefix=1
        - id: raporting-service
          uri: lb://raporting-service
          predicates:
            - Path=/raporting-service/**
          filters:
            - StripPrefix=1
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store-service/**
          filters:
            - StripPrefix=1
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: store
        url: /v3/api-docs/store-service
      - name: ordersystem
        url: /v3/api-docs/ordersystem-service
      - name: raporting
        url: /v3/api-docs/raporting-service


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1

management:
  endpoint:
    health:
      show-components: always
      show-details: always