server:
  port: 8760
spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
      discovery:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ordersystem-service
          uri: lb://ordersystem-service
          predicates:
            - Path=/ordersystem-service/**
          filters:
            - StripPrefix=1
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/reporting-service/**
          filters:
            - StripPrefix=1
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store-service/**
          filters:
            - StripPrefix=1
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
# To change to Local only profile
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**
# To change to OpenApi only profile
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
logging:
  level:
    org:
      springframework: info

springdoc:
  swagger-ui:
    urls:
      - name: store
        url: /v3/api-docs/store-service
      - name: ordersystem
        url: /v3/api-docs/ordersystem-service
      - name: reporting
        url: /v3/api-docs/reporting-service
    enabled: true


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1
    enabled: true

management:
  endpoint:
    health:
      show-components: always
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false


---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    kubernetes:
      enabled: true
      discovery:
        primary-port-name: 8760
        enabled: true
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration


eureka:
  client:
    enabled: false
