spring:
  application:
    name: ordersystem-service
  main:
    banner-mode: "off"

logging:
  level:
    org:
      springframework: error

server:
  port: 8762

info:
  app:
    name: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info