spring:
  application:
    name: registry

server:
  port: 8761
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    region: region1
    serviceUrl:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1
  instance:
    hostname: registry
    metadata-map:
      zone: zone1