spring:
  application:
    name: registry

server:
  port: 8761
  forward-headers-strategy: framework

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      zone1: http://registry:8761/eureka/
  instance:
    hostname: registry
    metadata-map:
      zone: zone1

management:
  endpoint:
    health:
      show-components: always
      show-details: always