spring:
  application:
    name: reporting-service
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework: info

server:
  port: 8764
  forward-headers-strategy: framework

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    region: region1
    service-url:
      zone1: http://registry:8761/eureka/
    availability-zones:
      region1: zone1

management:
  endpoint:
    health:
      show-components: always
      show-details: always
      enabled: true

---
spring:
  config:
    activate:
      on-profile: gcp

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://postgresql:5432/postgres
  jpa:
    hibernate:
      ddl-auto: none